---
title: JFDC Cookbook
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  recipes:
    title: Recipes
    output: true
    permalink: /:path/
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
tagline: A collection of recipies we like to cook
email: dc@damon.com.au
description: Yummy food
baseurl: "/"
url: ''
twitter_username: damo
instagram_username: damo.photo
facebook_username: 
markdown: kramdown
highlighter: pygmentize
exclude:
- node_modules
- gulpfile.js
- package.json
plugins:
- jekyll-feed
- jekyll-paginate
permalink: pretty
sass:
  sass_dir: css
